// week_4/React_App/src/App.js
import React, { useState } from "react";
import CourseList from "./CourseList";

function App() {
  const [courses, setCourses] = useState([]);

  const addCourse = () => {
    setCourses([...courses, { name: "React Basics", code: "RE101" }]);
  };

  return (
    <div>
      <h1>React Course Manager</h1>
      <button onClick={addCourse}>Add Course</button>
      <CourseList courses={courses} />
    </div>
  );
}

export default App;

// week_4/Vue_App/src/App.vue
<template>
  <div>
    <h1>Vue Course Manager</h1>
    <button @click="addCourse">Add Course</button>
    <CourseList :courses="courses" />
  </div>
</template>

<script>
import CourseList from "./CourseList.vue";

export default {
  components: { CourseList },
  data() {
    return {
      courses: []
    };
  },
  methods: {
    addCourse() {
      this.courses.push({ name: "Vue Basics", code: "VU101" });
    }
  }
};
</script>
